import type { Priority, SectorKey, SectorDef, Profile, Screen } from "./types";

export const defaultPriorities: Priority[] = ["customers","compliance","credit","efficiency","supply","reputation"];
export const missionCatalog = [
  {icon:"DATA",it:"La fabbrica dei dati ESG",en:"The ESG data factory",itSub:"Baseline ESG e qualità dei dati",enSub:"ESG baseline and data quality",value:"DATA FOUNDATION"},
  {icon:"ENERGY",it:"Energia e decarbonizzazione",en:"Energy and decarbonization",itSub:"Consumi, anomalie e costi operativi",enSub:"Consumption, anomalies and operating cost",value:"PERFORMANCE"},
  {icon:"SCOPE 3",it:"Il coinvolgimento della supply chain",en:"Supply chain engagement",itSub:"Fornitori, acquisti e catena del valore",enSub:"Suppliers, procurement and value chain",value:"SUPPLY CHAIN"},
  {icon:"AUDIT",it:"Reporting e performance",en:"Reporting and performance",itSub:"GHG reporting, workflow e dashboard",enSub:"GHG reporting, workflows and dashboards",value:"REPORTING"},
  {icon:"2035",it:"La rotta verso Net Zero",en:"The route to Net Zero",itSub:"Scenari, investimenti e decarbonizzazione",enSub:"Scenarios, investment and decarbonisation",value:"PLANNING"},
  {icon:"CSRD",it:"Framework ESG e disclosure",en:"ESG frameworks and disclosure",itSub:"CSRD, ESRS, GRI, SASB, CDP e mappatura requisiti",enSub:"CSRD, ESRS, GRI, SASB, CDP and requirements mapping",value:"FRAMEWORK"}
];

export const imageFor = (profile: Profile, screen: Screen) => `./characters/${profile}-${screen === "decision" || screen === "asis" ? "thoughtful" : screen === "negative" ? "negative" : screen === "success" ? "success" : "neutral"}.png`;

export const SECTORS:Record<SectorKey,SectorDef>={
  manifatturiero:{label:{it:"Gruppo manifatturiero",en:"Manufacturing group"},dimLabel:{it:"Dimensione economica",en:"Economic size"},dimUnit:{it:"€mln ricavi",en:"€M revenue"},opsLabel:{it:"Unità operative",en:"Operational units"},opsUnit:{it:"stabilimenti",en:"Plants"},defaults:[100,3,5,1,500]},
  bancario:{label:{it:"Gruppo bancario",en:"Banking group"},dimLabel:{it:"Attivi",en:"Assets"},dimUnit:{it:"€mld attivi",en:"€B assets"},opsLabel:{it:"Filiali",en:"Branches"},opsUnit:{it:"filiali",en:"Branches"},defaults:[30,150,5,2,3000]},
  assicurativo:{label:{it:"Gruppo assicurativo",en:"Insurance group"},dimLabel:{it:"Premi",en:"Premiums"},dimUnit:{it:"€mld premi",en:"€B premiums"},opsLabel:{it:"Agenzie",en:"Agencies"},opsUnit:{it:"agenzie",en:"Agencies"},defaults:[1,300,10,2,1000]},
  utilities:{label:{it:"Gruppo utilities",en:"Utilities group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mld ricavi",en:"€B revenue"},opsLabel:{it:"Impianti",en:"Plants"},opsUnit:{it:"impianti",en:"Plants"},defaults:[1,30,20,2,3000]},
  distribuzione:{label:{it:"Gruppo distribuzione/GDO",en:"Retail/Distribution group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mld ricavi",en:"€B revenue"},opsLabel:{it:"Punti vendita",en:"Stores"},opsUnit:{it:"punti vendita",en:"Stores"},defaults:[1,100,10,2,5000]},
  farmaceutico:{label:{it:"Gruppo farmaceutico",en:"Pharma group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mln ricavi",en:"€M revenue"},opsLabel:{it:"Stabilimenti/laboratori",en:"Plants/labs"},opsUnit:{it:"stabilimenti/laboratori",en:"Plants/labs"},defaults:[500,4,8,1,1500]},
  sanitario:{label:{it:"Gruppo sanitario",en:"Healthcare group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mln ricavi",en:"€M revenue"},opsLabel:{it:"Ospedali/cliniche",en:"Hospitals/clinics"},opsUnit:{it:"ospedali/cliniche",en:"Hospitals/clinics"},defaults:[500,15,10,2,5000]},
  logistico:{label:{it:"Gruppo logistico",en:"Logistics group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mln ricavi",en:"€M revenue"},opsLabel:{it:"Hub/magazzini",en:"Hubs/warehouses"},opsUnit:{it:"hub/magazzini",en:"Hubs/warehouses"},defaults:[500,30,15,1,3000]},
  alberghiero:{label:{it:"Gruppo alberghiero",en:"Hotel group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mln ricavi",en:"€M revenue"},opsLabel:{it:"Hotel",en:"Hotels"},opsUnit:{it:"hotel",en:"Hotels"},defaults:[300,30,5,1,2000]},
  telecomunicazioni:{label:{it:"Gruppo telecomunicazioni",en:"Telecom group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mld ricavi",en:"€B revenue"},opsLabel:{it:"Siti di rete",en:"Network sites"},opsUnit:{it:"siti di rete",en:"Network sites"},defaults:[1,5000,30,5,4000]},
  trasporti:{label:{it:"Gruppo trasporti",en:"Transport group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mld ricavi",en:"€B revenue"},opsLabel:{it:"Mezzi/stazioni",en:"Vehicles/stations"},opsUnit:{it:"mezzi/stazioni",en:"Vehicles/stations"},defaults:[1,1000,20,2,6000]},
  costruzioni:{label:{it:"Gruppo costruzioni",en:"Construction group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mln ricavi",en:"€M revenue"},opsLabel:{it:"Cantieri",en:"Sites"},opsUnit:{it:"cantieri",en:"Construction sites"},defaults:[500,20,10,1,2000]},
  immobiliare:{label:{it:"Gruppo immobiliare",en:"Real estate group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mln ricavi",en:"€M revenue"},opsLabel:{it:"Immobili",en:"Properties"},opsUnit:{it:"immobili",en:"Properties"},defaults:[300,100,10,1,500]},
  media:{label:{it:"Gruppo media",en:"Media group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mln ricavi",en:"€M revenue"},opsLabel:{it:"Testate/canali",en:"Titles/channels"},opsUnit:{it:"testate/canali",en:"Titles/channels"},defaults:[300,10,8,2,1000]},
  tecnologico:{label:{it:"Gruppo tecnologico/IT",en:"Tech/IT group"},dimLabel:{it:"Ricavi",en:"Revenue"},dimUnit:{it:"€mln ricavi",en:"€M revenue"},opsLabel:{it:"Strutture operative",en:"Operational units"},opsUnit:{it:"strutture operative",en:"Operational units"},defaults:[300,5,15,5,2000]},
  pa:{label:{it:"Pubblica amministrazione",en:"Public administration"},dimLabel:{it:"Bilancio",en:"Budget"},dimUnit:{it:"€mld bilancio",en:"€B budget"},opsLabel:{it:"Strutture",en:"Structures"},opsUnit:{it:"strutture",en:"Structures"},defaults:[1,100,50,3,5000]},
  universitario:{label:{it:"Gruppo universitario",en:"University group"},dimLabel:{it:"Bilancio",en:"Budget"},dimUnit:{it:"€mln bilancio",en:"€M budget"},opsLabel:{it:"Campus/dipartimenti",en:"Campuses/depts"},opsUnit:{it:"campus e dipartimenti",en:"Campuses and departments"},defaults:[500,30,30,2,4000]},
  nonprofit:{label:{it:"Fondazione/non profit",en:"Foundation/non-profit"},dimLabel:{it:"Risorse annue",en:"Annual resources"},dimUnit:{it:"€mln risorse annue",en:"€M annual resources"},opsLabel:{it:"Progetti/centri",en:"Projects/centres"},opsUnit:{it:"progetti/centri",en:"Projects/centres"},defaults:[100,20,10,1,500]},
};
export const SECTOR_KEYS=Object.keys(SECTORS) as SectorKey[];
export const DF_REQUIREMENTS:{id:string,it:string,en:string,critIt:string,critEn:string,capIt:string,capEn:string,toBeIt:string,toBeEn:string,benIt:string,benEn:string}[]=[
  {id:"df1",it:"Raccogliere dati ESG da fonti e formati diversi",en:"Collect ESG data from different sources and formats",
    critIt:"I dati sono dispersi tra ERP, e-mail, file CSV e portali separati: ogni raccolta richiede estrazione e riconciliazione manuale.",critEn:"Data is scattered across ERP systems, emails, CSV files and separate portals — every collection cycle requires manual extraction and reconciliation.",
    capIt:"Envizi acquisisce e consolida dati da sistemi aziendali, API, web form, survey e caricamenti massivi in un unico repository.",capEn:"Envizi ingests and consolidates data from enterprise systems, APIs, web forms, surveys and bulk uploads into a single repository.",
    toBeIt:"Un flusso automatizzato porta ogni fonte dati direttamente in Envizi, senza passaggi manuali intermedi.",toBeEn:"An automated flow brings every data source directly into Envizi, with no manual intermediate steps.",
    benIt:"Riduce la frammentazione e offre un punto di accesso unico alle informazioni ESG.",benEn:"Reduces fragmentation and provides a single access point for all ESG information."},
  {id:"df2",it:"Disporre di un'unica fonte affidabile per tutti i dati ESG",en:"Have a single reliable source for all ESG data",
    critIt:"Versioni parallele dei dati circolano su fogli diversi; non esiste un master record univoco su cui management e auditor possano fare affidamento.",critEn:"Parallel data versions circulate across different spreadsheets — there is no single master record that management and auditors can rely on.",
    capIt:"Envizi crea un sistema centralizzato e autorevole per dati ambientali, sociali e di governance, con accesso controllato per ruolo.",capEn:"Envizi creates a centralised, authoritative system for environmental, social and governance data, with role-based access control.",
    toBeIt:"Un unico sistema di record elimina le versioni parallele e diventa la fonte di riferimento per ogni decisione e disclosure.",toBeEn:"A single system of record eliminates parallel versions and becomes the reference source for every decision and disclosure.",
    benIt:"Evita versioni contrastanti dei dati e aumenta la fiducia di management, auditor e stakeholder.",benEn:"Avoids conflicting data versions and increases trust among management, auditors and stakeholders."},
  {id:"df3",it:"Uniformare dati con unità, valute e periodi differenti",en:"Normalise data with different units, currencies and periods",
    critIt:"Unità di misura, valute e periodi variano tra sedi: confrontare o aggregare i dati richiede rielaborazioni manuali ripetitive.",critEn:"Units of measure, currencies and periods vary across sites — comparing or aggregating data requires repetitive manual rework.",
    capIt:"Envizi normalizza automaticamente unità, valute e periodi, rendendo i dati aggregabili e confrontabili senza intervento manuale.",capEn:"Envizi automatically normalises units, currencies and periods, making data aggregable and comparable without manual intervention.",
    toBeIt:"Tutti i dati sono espressi in unità coerenti: i confronti tra sedi e periodi sono immediati e affidabili.",toBeEn:"All data is expressed in consistent units — comparisons across sites and periods are immediate and reliable.",
    benIt:"Riduce le elaborazioni manuali e consente confronti coerenti tra sedi, società e periodi.",benEn:"Reduces manual processing and enables consistent comparisons across sites, entities and periods."},
  {id:"df4",it:"Rappresentare una struttura organizzativa complessa",en:"Represent a complex, evolving organisational structure",
    critIt:"Le gerarchie organizzative cambiano spesso; aggiornare la struttura nei fogli di calcolo rompe le serie storiche e richiede riconciliazioni.",critEn:"Organisational hierarchies change frequently — updating the structure in spreadsheets breaks historical series and requires reconciliation.",
    capIt:"Envizi organizza i dati attraverso gerarchie flessibili per società, sedi, portafogli, aree geografiche e centri di costo.",capEn:"Envizi organises data through flexible hierarchies for companies, locations, portfolios, geographies and cost centres.",
    toBeIt:"La struttura organizzativa è gestita centralmente in Envizi: ogni variazione si riflette automaticamente su report e dashboard senza rielaborazioni.",toBeEn:"The organisational structure is managed centrally in Envizi — every change is automatically reflected across reports and dashboards without rework.",
    benIt:"Consente di analizzare e rendicontare i dati secondo diversi perimetri organizzativi e stakeholder.",benEn:"Enables analysis and reporting across different organisational perimeters and stakeholders."},
  {id:"df5",it:"Gestire dati ambientali e sociali sulla stessa piattaforma",en:"Manage environmental and social data on the same platform",
    critIt:"Dati ambientali e indicatori sociali vivono su sistemi separati; costruire una vista ESG integrata richiede esportazioni ed elaborazioni manuali.",critEn:"Environmental data and social indicators live in separate systems — building an integrated ESG view requires manual exports and processing.",
    capIt:"Envizi raccoglie e aggrega consumi, emissioni, acqua e rifiuti insieme a indicatori HR come dipendenti, incidenti, formazione e diversità.",capEn:"Envizi collects and aggregates energy, emissions, water and waste alongside HR indicators such as headcount, incidents, training and diversity.",
    toBeIt:"Un'unica piattaforma copre tutti gli indicatori ESG: la vista integrata è disponibile senza esportazioni o riconciliazioni.",toBeEn:"A single platform covers all ESG indicators — the integrated view is available without exports or reconciliation.",
    benIt:"Offre una visione ESG integrata senza dover mantenere archivi e processi separati.",benEn:"Provides an integrated ESG view without maintaining separate repositories and processes."},
  {id:"df6",it:"Identificare dati mancanti, incoerenti o anomali",en:"Identify missing, inconsistent or anomalous data",
    critIt:"I dati errati o incompleti vengono scoperti tardi, spesso solo in fase di reporting, quando correggerli è costoso e rallenta la chiusura.",critEn:"Erroneous or incomplete data is discovered late — often only during reporting — when correcting it is costly and delays the close.",
    capIt:"Envizi applica regole di validazione, alert, controlli di completezza e meccanismi di stima per i dati mancanti.",capEn:"Envizi applies validation rules, alerts, completeness checks and estimation mechanisms for missing data.",
    toBeIt:"I problemi di qualità sono segnalati in tempo reale, prima che raggiungano i report; il team interviene subito, non a consuntivo.",toBeEn:"Quality issues are flagged in real time, before they reach reports — the team acts immediately, not after the close.",
    benIt:"Riduce il tempo dedicato ai controlli manuali e migliora la qualità delle informazioni prima del reporting.",benEn:"Reduces time spent on manual checks and improves information quality ahead of reporting."},
  {id:"df7",it:"Ricostruire l'origine e le modifiche di ogni dato",en:"Trace the origin and changes of every data point",
    critIt:"In assenza di tracciabilità, rispondere a una richiesta di audit significa cercare e-mail, file e versioni precedenti dei fogli per ore o giorni.",critEn:"Without traceability, responding to an audit request means searching emails, files and previous spreadsheet versions for hours or days.",
    capIt:"Envizi conserva evidenze, record di dettaglio e tracciabilità completa dei dati usati nei calcoli e nei report.",capEn:"Envizi retains evidence, detail records and full traceability of data used in calculations and reports.",
    toBeIt:"Ogni dato è tracciabile dalla fonte al report in pochi clic: audit e assurance si gestiscono senza ricerche manuali.",toBeEn:"Every data point is traceable from source to report in a few clicks — audits and assurance are handled without manual searches.",
    benIt:"Facilita verifiche, assurance e audit, rendendo i risultati ESG più difendibili.",benEn:"Facilitates verifications, assurance and audits, making ESG results more defensible."},
  {id:"df8",it:"Automatizzare il calcolo delle emissioni Scope 1, 2 e 3",en:"Automate the calculation of Scope 1, 2 and 3 emissions",
    critIt:"I calcoli delle emissioni sono eseguiti manualmente su fogli complessi: errori nelle formule o nei fattori passano inosservati fino all'assurance.",critEn:"Emission calculations are performed manually on complex spreadsheets — formula or factor errors go unnoticed until assurance.",
    capIt:"Envizi trasforma i dati di attività in emissioni con un motore di calcolo strutturato e metodologie allineate al GHG Protocol.",capEn:"Envizi transforms activity data into emissions using a structured calculation engine aligned with the GHG Protocol.",
    toBeIt:"Il calcolo GHG è automatico, trasparente e verificabile: nessuna formula manuale, nessun rischio di errori silenti.",toBeEn:"GHG calculation is automatic, transparent and verifiable — no manual formulas, no risk of silent errors.",
    benIt:"Riduce il rischio di errori nei calcoli e libera tempo per analisi e iniziative di decarbonizzazione.",benEn:"Reduces calculation error risk and frees time for analysis and decarbonisation initiatives."},
  {id:"df9",it:"Disporre di fattori di emissione aggiornati e gestiti centralmente",en:"Have up-to-date emission factors managed centrally",
    critIt:"I team cercano e aggiornano manualmente i fattori di emissione: versioni diverse circolano tra sedi e anni, rendendo i confronti inaffidabili.",critEn:"Teams manually search for and update emission factors — different versions circulate across sites and years, making comparisons unreliable.",
    capIt:"Envizi mette a disposizione una libreria gestita di oltre 40.000 fattori di emissione, aggiornata nel servizio SaaS, più supporto a fattori custom.",capEn:"Envizi provides a managed library of over 40,000 emission factors, updated in the SaaS service, plus support for custom factors.",
    toBeIt:"I fattori sono aggiornati centralmente da IBM: ogni nuovo calcolo usa automaticamente la versione corrente, senza interventi del team.",toBeEn:"Factors are updated centrally by IBM — every new calculation automatically uses the current version, with no team intervention.",
    benIt:"Elimina la ricerca manuale dei fattori e rende più coerenti i risultati tra paesi e periodi.",benEn:"Eliminates manual factor research and makes results more consistent across countries and periods."},
  {id:"df10",it:"Scalare la raccolta riducendo dipendenza dai fogli di calcolo",en:"Scale data collection while reducing spreadsheet dependency",
    critIt:"All'aumentare di sedi e contributori, i fogli di calcolo diventano ingestibili: errori, versioni bloccate e tempi di raccolta crescono in modo non lineare.",critEn:"As sites and contributors grow, spreadsheets become unmanageable — errors, locked versions and collection times increase non-linearly.",
    capIt:"Envizi automatizza i flussi tramite connettori, API, template e workflow, con modalità guidate per i contributori occasionali.",capEn:"Envizi automates flows via connectors, APIs, templates and workflows, with guided modes for occasional contributors.",
    toBeIt:"Il processo scala a decine di sedi e centinaia di utenti senza aggiungere complessità operativa o rischio di errore.",toBeEn:"The process scales to dozens of sites and hundreds of users without adding operational complexity or error risk.",
    benIt:"Consente di estendere il processo a più sedi e utenti senza aumentare proporzionalmente tempi, errori e carico operativo.",benEn:"Enables you to extend the process to more sites and users without proportionally increasing time, errors and operational load."},
];
export const RF_REQUIREMENTS:{id:string,it:string,en:string,capIt:string,capEn:string,benIt:string,benEn:string}[]=[
  {id:"rf1",it:"Calcolare l'inventario GHG Scope 1 e 2 con metodi location-based e market-based",en:"Calculate the Scope 1 and 2 GHG inventory using location-based and market-based methods",capIt:"IBM Envizi governa fattori di emissione, metodologie e calcoli Scope 1–2, supportando sia il metodo location-based che market-based e producendo inventari riconciliati.",capEn:"IBM Envizi governs emission factors, methodologies and Scope 1–2 calculations, supporting both location-based and market-based methods and producing reconciled inventories.",benIt:"Elimina le riconciliazioni manuali tra metodi e riduce il rischio di errori nei calcoli GHG.",benEn:"Eliminates manual reconciliation between methods and reduces the risk of errors in GHG calculations."},
  {id:"rf2",it:"Calcolare le emissioni Scope 3 per categoria GHG Protocol",en:"Calculate Scope 3 emissions by GHG Protocol category",capIt:"IBM Envizi supporta il calcolo delle principali categorie Scope 3 con fattori e metodi coerenti con il GHG Protocol, a partire dai dati già presenti nel sistema.",capEn:"IBM Envizi supports the calculation of the main Scope 3 categories with GHG Protocol-aligned factors and methods, drawing from data already held in the system.",benIt:"Riduce le elaborazioni manuali e rende comparabili le categorie Scope 3 nel tempo e tra sedi.",benEn:"Reduces manual processing and makes Scope 3 categories comparable over time and across sites."},
  {id:"rf3",it:"Analizzare le emissioni per fonte, sito e periodo in un'unica vista",en:"Analyse emissions by source, site and period in a single view",capIt:"IBM Envizi fornisce dashboard preconfigurate per analizzare Scope 1–2 per sito, fonte e periodo, con drill-down dai totali aggregati ai dati di dettaglio.",capEn:"IBM Envizi provides preconfigured dashboards to analyse Scope 1–2 by site, source and period, with drill-down from aggregated totals to detail-level data.",benIt:"Consente a management e funzioni operative di confrontare le performance senza necessità di estrazioni manuali.",benEn:"Allows management and operational teams to compare performance without manual extractions."},
  {id:"rf4",it:"Identificare gli hotspot emissivi e le principali fonti di emissione",en:"Identify emission hotspots and primary emission sources",capIt:"IBM Envizi permette di analizzare la distribuzione delle emissioni per fonte, categoria e sito, evidenziando le voci che incidono maggiormente sull'inventario totale.",capEn:"IBM Envizi lets you analyse the distribution of emissions by source, category and site, highlighting the entries with the greatest impact on the total inventory.",benIt:"Orienta le priorità di decarbonizzazione e supporta le decisioni di investimento con dati verificabili.",benEn:"Guides decarbonisation priorities and supports investment decisions with verifiable data."},
  {id:"rf5",it:"Produrre report preconfigurati pronti per la disclosure",en:"Produce preconfigured reports ready for disclosure",capIt:"IBM Envizi include report preconfigurati per i principali requisiti di disclosure GHG, esportabili e pronti per la revisione e l'approvazione.",capEn:"IBM Envizi includes preconfigured reports for the main GHG disclosure requirements, exportable and ready for review and approval.",benIt:"Riduce il tempo di preparazione della disclosure e garantisce coerenza tra i cicli di rendicontazione.",benEn:"Reduces disclosure preparation time and ensures consistency across reporting cycles."},
  {id:"rf6",it:"Creare dashboard e PowerReports personalizzabili per stakeholder diversi",en:"Create customisable dashboards and PowerReports for different stakeholders",capIt:"IBM Envizi supporta la creazione di PowerReports personalizzabili con Microsoft Power BI Embedded, integrati nei dati del sistema senza esportazioni manuali.",capEn:"IBM Envizi supports the creation of customisable PowerReports with embedded Microsoft Power BI, integrated directly into system data without manual exports.",benIt:"Consente di produrre viste dedicate per CdA, banche, clienti e auditor dallo stesso dato auditabile.",benEn:"Enables dedicated views for Board, banks, clients and auditors from the same auditable data source."},
  {id:"rf7",it:"Risalire dai report ai dati e alle metodologie sottostanti",en:"Trace back from reports to the underlying data and methodologies",capIt:"IBM Envizi mantiene la tracciabilità completa dal valore presentato in dashboard o report al dato originale, al fattore applicato e al metodo utilizzato.",capEn:"IBM Envizi maintains full traceability from the value shown in a dashboard or report back to the original data, the factor applied and the method used.",benIt:"Facilita l'assurance esterna e risponde alle richieste di auditor e regolatori con evidenze dirette.",benEn:"Facilitates external assurance and responds to auditor and regulator requests with direct evidence."},
  {id:"rf8",it:"Monitorare i KPI GHG nel tempo e rispetto ai target",en:"Monitor GHG KPIs over time and against targets",capIt:"IBM Envizi permette di confrontare i valori effettivi con i target, visualizzare l'andamento nel tempo e ricevere alert su scostamenti significativi.",capEn:"IBM Envizi lets you compare actual values against targets, visualise trends over time and receive alerts on significant deviations.",benIt:"Rende il monitoraggio della decarbonizzazione continuo e visibile a tutta l'organizzazione.",benEn:"Makes decarbonisation monitoring continuous and visible across the organisation."},
];
export const EF_REQUIREMENTS:{id:string,it:string,en:string,capIt:string,capEn:string,benIt:string,benEn:string}[]=[
  {id:"ef1",it:"Acquisire automaticamente i dati intervallari dai contatori digitali",en:"Automatically capture interval data from digital meters",capIt:"Envizi Interval Meter Analytics acquisisce letture quasi in tempo reale dai contatori, le normalizza e le rende disponibili per l'analisi senza interventi manuali.",capEn:"Envizi Interval Meter Analytics captures near-real-time readings from meters, normalises them and makes them available for analysis without manual intervention.",benIt:"Elimina il caricamento manuale delle letture e rende visibili anomalie e picchi non appena si verificano.",benEn:"Eliminates manual reading uploads and makes anomalies and peaks visible as soon as they occur."},
  {id:"ef2",it:"Analizzare le bollette per sito, utility, costo e variazione anomala",en:"Analyse utility bills by site, utility type, cost and anomalous variance",capIt:"Envizi Utility Bill Analytics consolida le fatture, identifica voci anomale e confronta i costi tra periodi e sedi.",capEn:"Envizi Utility Bill Analytics consolidates bills, identifies anomalous items and compares costs across periods and sites.",benIt:"Riduce il tempo di revisione delle fatture e anticipa variazioni di costo prima del consuntivo.",benEn:"Reduces bill review time and anticipates cost variances before month-end."},
  {id:"ef3",it:"Normalizzare i KPI energetici per meteo e variabili operative",en:"Normalise energy KPIs for weather and operational variables",capIt:"Envizi supporta la regressione e la normalizzazione dei consumi in base a variabili come gradi-giorno e unità produttive.",capEn:"Envizi supports regression and normalisation of consumption against variables such as degree-days and production units.",benIt:"Rende confrontabili i consumi tra stabilimenti con condizioni climatiche e produttive diverse.",benEn:"Makes consumption comparable across sites with different climatic and production conditions."},
  {id:"ef4",it:"Generare alert automatici su picchi, sprechi e consumi fuori andamento",en:"Generate automatic alerts on peaks, waste and out-of-pattern consumption",capIt:"Envizi Interval Meter Analytics genera alert configurabili su soglie, picchi di domanda e consumi anomali, assegnabili all'Energy Manager.",capEn:"Envizi Interval Meter Analytics generates configurable alerts on thresholds, demand peaks and anomalous consumption, assignable to the Energy Manager.",benIt:"Riduce il tempo di reazione agli sprechi e documenta ogni segnalazione per il follow-up.",benEn:"Reduces response time to waste events and documents each alert for follow-up."},
  {id:"ef5",it:"Confrontare le performance energetiche tra stabilimenti e rispetto ai target",en:"Benchmark energy performance across sites and against targets",capIt:"Envizi permette di confrontare intensità energetiche tra sedi, visualizzare l'andamento rispetto ai target e individuare gli impianti con le maggiori opportunità di miglioramento.",capEn:"Envizi lets you compare energy intensity across sites, track progress against targets and identify the plants with the greatest improvement potential.",benIt:"Orienta le priorità di efficienza verso i siti con il maggiore impatto su costi ed emissioni.",benEn:"Directs efficiency priorities towards the sites with the greatest impact on cost and emissions."},
  {id:"ef6",it:"Valutare economicamente e ambientalmente gli interventi di efficienza",en:"Assess energy efficiency measures economically and environmentally",capIt:"Envizi Sustainability Program Tracking e Scenario Modeler permettono di stimare costi, risparmi e CO₂e evitata per ciascun intervento.",capEn:"Envizi Sustainability Program Tracking and Scenario Modeler let you estimate costs, savings and avoided CO₂e for each measure.",benIt:"Supporta la selezione degli investimenti con dati verificabili e collegati alla baseline ESG.",benEn:"Supports investment selection with verifiable data linked to the ESG baseline."},
];
export const SC_REQUIREMENTS:{id:string,it:string,en:string,capIt:string,capEn:string,benIt:string,benEn:string}[]=[
  {id:"sc1",it:"Coprire le principali categorie Scope 3 del GHG Protocol",en:"Cover the main GHG Protocol Scope 3 categories",capIt:"Envizi Scope 3 GHG Accounting supporta il calcolo delle categorie GHG Protocol più rilevanti, con fattori di emissione gestiti centralmente e metodi coerenti.",capEn:"Envizi Scope 3 GHG Accounting supports the calculation of the most material GHG Protocol categories using centrally managed emission factors and consistent methods.",benIt:"Estende la copertura dell'inventario oltre gli acquisti e riduce le elaborazioni manuali per ciascuna categoria.",benEn:"Extends inventory coverage beyond procurement and reduces manual processing per category."},
  {id:"sc2",it:"Coinvolgere i fornitori con questionari strutturati e workflow di raccolta",en:"Engage suppliers with structured questionnaires and collection workflows",capIt:"Envizi Surveys + Assessments gestisce domande multiple, allegati, commenti, scadenze, stato delle risposte e workflow di approvazione.",capEn:"Envizi Surveys + Assessments manages multiple question types, attachments, comments, due dates, response status and approval workflows.",benIt:"Riduce i solleciti manuali e rende le risposte comparabili tra fornitori e periodi.",benEn:"Reduces manual follow-up and makes responses comparable across suppliers and periods."},
  {id:"sc3",it:"Integrare i dati ERP per il calcolo delle emissioni da acquisti",en:"Integrate ERP data for purchase-based emission calculations",capIt:"Envizi Supply Chain Intelligence acquisisce automaticamente righe d'ordine e transazioni da sistemi ERP e finanziari per le categorie 1 e 2.",capEn:"Envizi Supply Chain Intelligence automatically ingests order lines and transactions from ERP and financial systems for categories 1 and 2.",benIt:"Elimina la raccolta manuale degli acquisti e aumenta la copertura e l'accuratezza delle emissioni cat. 1 e 2.",benEn:"Eliminates manual procurement data collection and improves coverage and accuracy for categories 1 and 2."},
  {id:"sc4",it:"Passare progressivamente dalle stime spend-based ai dati supplier-specific e PCF",en:"Progressively move from spend-based estimates to supplier-specific data and PCFs",capIt:"Envizi Supply Chain Intelligence supporta una gerarchia di metodi: da fattori medi a dati corporate, supplier-specific e Product Carbon Footprint.",capEn:"Envizi Supply Chain Intelligence supports a method hierarchy: from average factors to corporate, supplier-specific and Product Carbon Footprint data.",benIt:"Migliora la qualità e la granularità dell'inventario Scope 3 progressivamente, senza riconfigurare il sistema.",benEn:"Improves Scope 3 inventory quality and granularity progressively without reconfiguring the system."},
  {id:"sc5",it:"Monitorare i tassi di risposta e la qualità dei dati ricevuti dai fornitori",en:"Monitor supplier response rates and the quality of data received",capIt:"Envizi Supply Chain Intelligence e Surveys offrono dashboard di engagement con tassi di completamento, qualità delle risposte e stato dei workflow.",capEn:"Envizi Supply Chain Intelligence and Surveys provide engagement dashboards with completion rates, response quality and workflow status.",benIt:"Rende visibile la copertura della supply chain e orienta le azioni di miglioramento verso i fornitori più critici.",benEn:"Makes supply chain coverage visible and directs improvement actions towards the most material suppliers."},
  {id:"sc6",it:"Integrare le risposte dei fornitori nella contabilità GHG senza riconciliazioni manuali",en:"Integrate supplier responses into GHG accounting without manual reconciliation",capIt:"I dati raccolti tramite Surveys e Supply Chain Intelligence confluiscono direttamente nei calcoli Scope 3, senza esportazioni o passaggi intermedi.",capEn:"Data collected via Surveys and Supply Chain Intelligence flows directly into Scope 3 calculations, without exports or intermediate steps.",benIt:"Riduce il rischio di errori nella riconciliazione e accelera il ciclo di chiusura dell'inventario Scope 3.",benEn:"Reduces reconciliation error risk and accelerates the Scope 3 inventory close cycle."},
];
export const PL_REQUIREMENTS:{id:string,it:string,en:string,capIt:string,capEn:string,benIt:string,benEn:string}[]=[
  {id:"pl1",it:"Costruire previsioni di emissione a partire dalla baseline ESG verificata",en:"Build emission forecasts from the verified ESG baseline",capIt:"Envizi Scenario Modeler parte dalla baseline certificata del sistema per costruire traiettorie di emissione future e scenari what-if.",capEn:"Envizi Scenario Modeler starts from the system-certified baseline to build future emission trajectories and what-if scenarios.",benIt:"Garantisce che i forecast siano collegati a dati verificati, non a stime manuali, aumentando la credibilità del piano.",benEn:"Ensures forecasts are linked to verified data, not manual estimates, increasing plan credibility."},
  {id:"pl2",it:"Confrontare scenari e combinazioni di iniziative rispetto al target Net Zero",en:"Compare scenarios and initiative combinations against the Net Zero target",capIt:"Envizi Scenario Modeler permette di creare e confrontare più scenari what-if, valutando combinazioni di iniziative per CapEx, OpEx e CO₂e evitata.",capEn:"Envizi Scenario Modeler lets you create and compare multiple what-if scenarios, evaluating initiative combinations for CapEx, OpEx and avoided CO₂e.",benIt:"Consente di identificare il mix ottimale di iniziative che chiude il gap verso il target con il budget disponibile.",benEn:"Enables identification of the optimal initiative mix that closes the target gap within the available budget."},
  {id:"pl3",it:"Ottimizzare il portafoglio di decarbonizzazione rispetto al budget disponibile",en:"Optimise the decarbonisation portfolio against the available budget",capIt:"Envizi Planning Analytics AddOn e Scenario Modeler supportano l'ottimizzazione del portafoglio per massimizzare le riduzioni di CO₂e nel rispetto dei vincoli di budget.",capEn:"Envizi Planning Analytics AddOn and Scenario Modeler support portfolio optimisation to maximise CO₂e reductions within budget constraints.",benIt:"Riduce la dipendenza da fogli di calcolo e semplifica le decisioni di allocazione del capitale con dati ESG integrati.",benEn:"Reduces spreadsheet dependency and simplifies capital allocation decisions with integrated ESG data."},
  {id:"pl4",it:"Monitorare l'esecuzione dei programmi e la spesa rispetto al piano",en:"Monitor programme execution and spend against the plan",capIt:"Envizi Sustainability Program Tracking registra milestone, avanzamento, spesa effettiva, risparmi realizzati e emissioni evitate per ciascun programma.",capEn:"Envizi Sustainability Program Tracking records milestones, progress, actual spend, realised savings and avoided emissions per programme.",benIt:"Rende l'esecuzione trasparente e verificabile, consentendo di aggiornare il piano se le condizioni cambiano.",benEn:"Makes execution transparent and verifiable, enabling plan updates if conditions change."},
  {id:"pl5",it:"Quantificare l'impatto finanziario degli investimenti in decarbonizzazione (IRR, NPV)",en:"Quantify the financial impact of decarbonisation investments (IRR, NPV)",capIt:"Envizi Sustainability Program Tracking include la valorizzazione economica delle iniziative con costi, risparmi attesi, IRR e NPV configurabili.",capEn:"Envizi Sustainability Program Tracking includes economic valuation of initiatives with configurable costs, expected savings, IRR and NPV.",benIt:"Rende il business case ESG difendibile davanti al CFO e ai finanziatori con dati verificabili e confrontabili.",benEn:"Makes the ESG business case defensible before the CFO and financiers with verifiable, comparable data."},
  {id:"pl6",it:"Aggiornare i target e le traiettorie al variare delle condizioni operative",en:"Update targets and trajectories as operational conditions change",capIt:"Envizi Target Setting + Tracking e Scenario Modeler permettono di aggiornare target e traiettorie quando cambiano dati, budget o priorità.",capEn:"Envizi Target Setting + Tracking and Scenario Modeler allow targets and trajectories to be updated when data, budgets or priorities change.",benIt:"Mantiene il piano Net Zero attuale e adattabile senza ricostruire l'analisi da zero a ogni revisione.",benEn:"Keeps the Net Zero plan current and adaptable without rebuilding the analysis from scratch at each review."},
];
export const FR_REQUIREMENTS:{id:string,it:string,en:string,capIt:string,capEn:string,benIt:string,benEn:string}[]=[
  {id:"fr1",it:"Gestire framework ESG (CSRD, ESRS, GRI, SASB, CDP) sempre aggiornati nel sistema",en:"Manage ESG frameworks (CSRD, ESRS, GRI, SASB, CDP) kept current in the system",capIt:"Envizi Sustainability Reporting Manager include una Framework Library gestita e aggiornata nel servizio SaaS, senza interventi manuali del team.",capEn:"Envizi Sustainability Reporting Manager includes a managed Framework Library kept current in the SaaS service, without manual team intervention.",benIt:"Elimina il confronto manuale tra versioni dei framework e riduce il rischio di perdere aggiornamenti normativi.",benEn:"Eliminates manual comparison between framework versions and reduces the risk of missing regulatory updates."},
  {id:"fr2",it:"Mappare i requisiti materiali e identificare i gap rispetto ai dati disponibili",en:"Map material requirements and identify gaps against available data",capIt:"Envizi Sustainability Reporting Manager supporta la mappatura dei requisiti, il tagging di materialità e l'identificazione dei gap rispetto ai dati già presenti nel sistema.",capEn:"Envizi Sustainability Reporting Manager supports requirements mapping, materiality tagging and gap identification against data already in the system.",benIt:"Rende visibile la copertura informativa per ciascun framework e orienta le azioni di raccolta verso i requisiti non ancora soddisfatti.",benEn:"Makes information coverage visible per framework and directs data collection towards requirements not yet met."},
  {id:"fr3",it:"Gestire il processo di raccolta con workflow, owner, reviewer e approvazioni",en:"Manage the collection process with workflows, owners, reviewers and approvals",capIt:"Envizi Sustainability Reporting Manager gestisce il workflow di raccolta con assignee, scadenze, evidenze, commenti e approvazioni tracciate.",capEn:"Envizi Sustainability Reporting Manager manages the collection workflow with assignees, due dates, evidence, comments and tracked approvals.",benIt:"Sostituisce la gestione via e-mail con un processo governato, tracciabile e auditabile da inizio a fine ciclo.",benEn:"Replaces email-based management with a governed, traceable and auditable process from start to end of cycle."},
  {id:"fr4",it:"Produrre output di disclosure riutilizzabili e pronti per l'assurance",en:"Produce reusable disclosure outputs ready for assurance",capIt:"Envizi Sustainability Reporting Manager genera risposte strutturate, allegati e export per i framework selezionati, tracciabili fino alla fonte del dato.",capEn:"Envizi Sustainability Reporting Manager generates structured responses, attachments and exports for selected frameworks, traceable to the data source.",benIt:"Riduce il tempo di preparazione della disclosure e rende le evidenze immediatamente disponibili per auditor e revisori.",benEn:"Reduces disclosure preparation time and makes evidence immediately available for auditors and reviewers."},
  {id:"fr5",it:"Integrare i calcoli GHG nei requisiti di disclosure senza doppia elaborazione",en:"Integrate GHG calculations into disclosure requirements without double processing",capIt:"I dati GHG già presenti in Envizi (Scope 1, 2 e 3) vengono richiamati direttamente dai framework attivi nel Sustainability Reporting Manager.",capEn:"GHG data already in Envizi (Scope 1, 2 and 3) is referenced directly by the active frameworks in the Sustainability Reporting Manager.",benIt:"Elimina la riconciliazione tra il modello GHG e i template di disclosure, riducendo errori e tempi di chiusura.",benEn:"Eliminates reconciliation between the GHG model and disclosure templates, reducing errors and close time."},
  {id:"fr6",it:"Mantenere un audit trail completo per ciascun requisito e dato comunicato",en:"Maintain a full audit trail for each requirement and disclosed data point",capIt:"Envizi conserva la tracciabilità di ogni dato comunicato: fonte, fattore applicato, workflow di approvazione e versione del framework.",capEn:"Envizi retains full traceability for every disclosed data point: source, applied factor, approval workflow and framework version.",benIt:"Risponde alle richieste di assurance esterna con evidenze dirette, riducendo il carico operativo del team ESG.",benEn:"Responds to external assurance requests with direct evidence, reducing the operational load on the ESG team."},
];
export const ESG_READINESS_IT=[
  {key:"primi" as EsgReadiness,label:"Primi passi — Readiness dati: bassa",desc:"L'organizzazione sta iniziando il percorso ESG. I dati sono pochi e frammentati. Cerca una soluzione per raccogliere i dati, capire cosa manca e organizzare le informazioni."},
  {key:"consolidamento" as EsgReadiness,label:"Consolidamento — Readiness dati: media",desc:"L'organizzazione dispone dei principali dati ESG, ma deve renderli completi, affidabili e confrontabili. Cerca una piattaforma per unificare e controllare i dati, calcolare le emissioni e preparare la rendicontazione."},
  {key:"decisioni" as EsgReadiness,label:"Decisioni ESG — Readiness dati: alta",desc:"L'organizzazione dispone di dati ESG strutturati e affidabili e vuole utilizzarli nelle decisioni aziendali. Cerca analisi, scenari e KPI per monitorare i risultati, gestire i rischi e raggiungere gli obiettivi ESG."},
];
export const ESG_READINESS_EN=[
  {key:"primi" as EsgReadiness,label:"First steps — Data readiness: low",desc:"The organisation is starting its ESG journey. Data is scarce and fragmented. Looking for a solution to collect data, identify gaps and organise information."},
  {key:"consolidamento" as EsgReadiness,label:"Consolidation — Data readiness: medium",desc:"The organisation has the main ESG data but needs to make it complete, reliable and comparable. Looking for a platform to unify and control data, calculate emissions and prepare reporting."},
  {key:"decisioni" as EsgReadiness,label:"ESG decisions — Data readiness: high",desc:"The organisation has structured, reliable ESG data and wants to use it in business decisions. Looking for analytics, scenarios and KPIs to monitor results, manage risks and achieve ESG targets."},
];
